import { useState, useEffect } from 'react';
import { History as HistoryIcon, Calendar, FileCode, TrendingUp, Download, Trash2, Eye, Filter } from 'lucide-react';
import DashboardLayout from './DashboardLayout';
import jsPDF from 'jspdf';


export default function History() {
  const [selectedFilter, setSelectedFilter] = useState('all');
  const [selectedPeriod, setSelectedPeriod] = useState('30');
  const [historyData, setHistoryData] = useState<any[]>([]);
  const [selectedAnalysis, setSelectedAnalysis] = useState<any>(null);
  const [showDetails, setShowDetails] = useState(false);
  const [selectedLanguageFilter, setSelectedLanguageFilter] = useState('all');

  useEffect(() => {
    // Check if user is logged in
    const currentUserData = localStorage.getItem('codeguard_current_user');
    if (!currentUserData) {
      return;
    }

    const currentUser = JSON.parse(currentUserData);

    // Load user-specific history
    const userHistoryKey = `history_${currentUser.id}`;
    const history = localStorage.getItem(userHistoryKey);
    if (history) {
      const parsedHistory = JSON.parse(history);
      const enhancedHistory = parsedHistory.map((item: any, index: number) => ({
        id: index + 1,
        ...item,
        language: item.language || 'python',
        linesOfCode: item.code ? item.code.split('\n').length : 0,
        issues: (item.summary?.critical || 0) + (item.summary?.high || 0) + (item.summary?.medium || 0),
        critical: item.summary?.critical || 0,
        high: item.summary?.high || 0,
        medium: item.summary?.medium || 0,
        low: 0,
        analysisTime: 'Real-time',
        date: item.timestamp || new Date().toLocaleString()
      }));
      setHistoryData(enhancedHistory);
    }
  }, []);

  // Filter history by selected language
  const filteredHistory = selectedLanguageFilter === 'all' 
    ? historyData 
    : historyData.filter(item => item.language.toLowerCase() === selectedLanguageFilter.toLowerCase());

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-400';
    if (score >= 75) return 'text-yellow-400';
    return 'text-red-400';
  };

  const getScoreBadge = (score: number) => {
    if (score >= 90) return 'bg-green-500/20 text-green-400 border-green-500/30';
    if (score >= 75) return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30';
    return 'bg-red-500/20 text-red-400 border-red-500/30';
  };

  const handleViewDetails = (item: any) => {
    setSelectedAnalysis(item);
    setShowDetails(true);
  };

  const handleDownload = (item: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 20;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(59, 130, 246);
    doc.text("CodeGuard AI - Analysis Report", pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Analysis Date: ${item.date}`, pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Quality Score
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Quality Score", 20, yPos);
    yPos += 10;
    
    doc.setFontSize(14);
    doc.setTextColor(34, 197, 94);
    doc.text(`${item.quality_score}/100`, 20, yPos);
    yPos += 15;

    // Issue Summary
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Issue Summary", 20, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.setTextColor(239, 68, 68);
    doc.text(`Critical: ${item.critical}`, 25, yPos);
    yPos += 8;

    doc.setTextColor(251, 146, 60);
    doc.text(`High: ${item.high}`, 25, yPos);
    yPos += 8;

    doc.setTextColor(234, 179, 8);
    doc.text(`Medium: ${item.medium}`, 25, yPos);
    yPos += 15;

    // Lines Analyzed
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Lines Analyzed: ${item.linesOfCode}`, 20, yPos);
    yPos += 10;
    doc.text(`Language: ${item.language}`, 20, yPos);
    yPos += 15;

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by CodeGuard AI", pageWidth / 2, pageHeight - 10, { align: 'center' });

    doc.save(`Analysis_Report_${item.id}.pdf`);
  };

  const handleDelete = (id: number) => {
    if (confirm('Are you sure you want to delete this analysis?')) {
      const currentUserData = localStorage.getItem('codeguard_current_user');
      if (!currentUserData) return;
      
      const currentUser = JSON.parse(currentUserData);
      const updatedHistory = historyData.filter(item => item.id !== id);
      setHistoryData(updatedHistory);
      
      // Update localStorage
      const userHistoryKey = `history_${currentUser.id}`;
      localStorage.setItem(userHistoryKey, JSON.stringify(updatedHistory));
    }
  };

  const handleExportAll = () => {
    if (filteredHistory.length === 0) {
      alert('No data to export');
      return;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 20;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(59, 130, 246);
    doc.text("CodeGuard AI - Complete History", pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Summary Stats
    const avgScore = Math.round(filteredHistory.reduce((acc, item) => acc + item.quality_score, 0) / filteredHistory.length);
    const totalIssues = filteredHistory.reduce((acc, item) => acc + item.issues, 0);

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Analysis: ${filteredHistory.length}`, 20, yPos);
    yPos += 8;
    doc.text(`Average Score: ${avgScore}/100`, 20, yPos);
    yPos += 8;
    doc.text(`Total Issues Found: ${totalIssues}`, 20, yPos);
    yPos += 15;

    // Individual Analyses
    doc.setFontSize(12);
    doc.text("Analysis History:", 20, yPos);
    yPos += 10;

    filteredHistory.forEach((item, index) => {
      if (yPos > pageHeight - 40) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text(`${index + 1}. ${item.date}`, 20, yPos);
      yPos += 6;
      doc.setTextColor(100, 100, 100);
      doc.text(`   Score: ${item.quality_score}/100 | Issues: ${item.issues} | Lines: ${item.linesOfCode}`, 20, yPos);
      yPos += 10;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by CodeGuard AI", pageWidth / 2, pageHeight - 10, { align: 'center' });

    doc.save(`CodeGuard_Complete_History_${new Date().getTime()}.pdf`);
  };

  const stats = filteredHistory.length > 0 ? {
    totalAnalysis: filteredHistory.length,
    avgScore: Math.round(filteredHistory.reduce((acc, item) => acc + item.quality_score, 0) / filteredHistory.length),
    totalIssues: filteredHistory.reduce((acc, item) => acc + item.issues, 0),
    totalLines: filteredHistory.reduce((acc, item) => acc + item.linesOfCode, 0)
  } : {
    totalAnalysis: 0,
    avgScore: 0,
    totalIssues: 0,
    totalLines: 0
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-3xl md:text-4xl text-white mb-2">Analysis History</h1>
          <p className="text-gray-400">Review your past code analysis results</p>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <div className="glass-card p-6 rounded-xl">
            <div className="flex items-center gap-3 mb-2">
              <HistoryIcon className="w-5 h-5 text-blue-400" />
              <span className="text-gray-400 text-sm">Total Analysis</span>
            </div>
            <p className="text-3xl text-white font-semibold">{stats.totalAnalysis}</p>
          </div>

          <div className="glass-card p-6 rounded-xl">
            <div className="flex items-center gap-3 mb-2">
              <TrendingUp className="w-5 h-5 text-green-400" />
              <span className="text-gray-400 text-sm">Avg Score</span>
            </div>
            <p className="text-3xl text-green-400 font-semibold">{stats.avgScore}/100</p>
          </div>

          <div className="glass-card p-6 rounded-xl">
            <div className="flex items-center gap-3 mb-2">
              <FileCode className="w-5 h-5 text-purple-400" />
              <span className="text-gray-400 text-sm">Total Lines</span>
            </div>
            <p className="text-3xl text-white font-semibold">{stats.totalLines}</p>
          </div>

          <div className="glass-card p-6 rounded-xl">
            <div className="flex items-center gap-3 mb-2">
              <Download className="w-5 h-5 text-yellow-400" />
              <span className="text-gray-400 text-sm">Issues Found</span>
            </div>
            <p className="text-3xl text-white font-semibold">{stats.totalIssues}</p>
          </div>
        </div>

        {/* Filters */}
        <div className="glass-card p-4 rounded-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <Filter className="w-5 h-5 text-gray-400" />
           <select 
           value={selectedLanguageFilter}
           onChange={(e) => setSelectedLanguageFilter(e.target.value)}
           className="px-4 py-2 bg-[#0B0F1A] border border-blue-500/30 rounded-lg text-white focus:outline-none focus:border-blue-500 transition-colors"
           >
           <option value="all">All Languages</option>
           <option value="python">Python</option>
           <option value="javascript">JavaScript</option>
           <option value="java">Java</option>
           <option value="cpp">C++</option>
           </select>
          </div>

          <div className="flex items-center gap-3">
            <Calendar className="w-5 h-5 text-gray-400" />
            <select 
            value={selectedPeriod}
            onChange={(e) => setSelectedPeriod(e.target.value)}
            className="px-4 py-2 bg-[#0B0F1A] border border-blue-500/30 rounded-lg text-white focus:outline-none focus:border-blue-500 transition-colors"
            >
            <option value="7">Last 7 days</option>
            <option value="30">Last 30 days</option>
            <option value="90">Last 90 days</option>
            <option value="all">All time</option> 
            </select>

            <button 
              onClick={handleExportAll}
              className="gradient-button px-4 py-2 rounded-lg text-white flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Export
            </button>
          </div>
        </div>

        {/* History Table */}
        {filteredHistory.length > 0 ? (
          <div className="glass-card rounded-xl overflow-hidden">
            {/* Desktop Table */}
            <div className="hidden lg:block overflow-x-auto">
              <table className="w-full">
                <thead className="bg-[#0B0F1A] border-b border-blue-500/20">
                  <tr>
                    <th className="text-left p-4 text-gray-400 font-medium">Date & Time</th>
                    <th className="text-left p-4 text-gray-400 font-medium">Language</th>
                    <th className="text-left p-4 text-gray-400 font-medium">Lines</th>
                    <th className="text-left p-4 text-gray-400 font-medium">Issues</th>
                    <th className="text-right p-4 text-gray-400 font-medium">Score</th>
                    <th className="text-right p-4 text-gray-400 font-medium">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredHistory.map((item) => (
                    <tr key={item.id} className="border-b border-blue-500/10 hover:bg-blue-500/5 transition-colors">
                      <td className="p-4">
                        <div className="flex items-center gap-2 text-gray-300">
                          <Calendar className="w-4 h-4 text-gray-500" />
                          {item.date}
                        </div>
                      </td>
                      <td className="p-4">
                        <span className="px-3 py-1 bg-blue-500/20 text-blue-400 rounded-full text-sm">
                          {item.language}
                        </span>
                      </td>
                      <td className="p-4 text-gray-300">{item.linesOfCode}</td>
                      <td className="p-4">
                        <div className="flex items-center gap-2">
                          {item.critical > 0 && (
                            <span className="px-2 py-1 bg-red-500/20 text-red-400 rounded text-xs">
                              {item.critical}C
                            </span>
                          )}
                          {item.high > 0 && (
                            <span className="px-2 py-1 bg-orange-500/20 text-orange-400 rounded text-xs">
                              {item.high}H
                            </span>
                          )}
                          {item.medium > 0 && (
                            <span className="px-2 py-1 bg-yellow-500/20 text-yellow-400 rounded text-xs">
                              {item.medium}M
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="p-4 text-right">
                        <span className={`px-3 py-1 rounded-full border text-sm ${getScoreBadge(item.quality_score)}`}>
                          {item.quality_score}/100
                        </span>
                      </td>
                      <td className="p-4">
                        <div className="flex items-center justify-end gap-2">
                          <button 
                            onClick={() => handleViewDetails(item)}
                            className="p-2 hover:bg-blue-500/20 rounded-lg transition-colors text-blue-400" 
                            title="View Details"
                          >
                            <Eye className="w-4 h-4" />
                          </button>
                          <button 
                            onClick={() => handleDownload(item)}
                            className="p-2 hover:bg-green-500/20 rounded-lg transition-colors text-green-400" 
                            title="Download Report"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                          <button 
                            onClick={() => handleDelete(item.id)}
                            className="p-2 hover:bg-red-500/20 rounded-lg transition-colors text-red-400" 
                            title="Delete"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Mobile View */}
            <div className="lg:hidden p-4 space-y-4">
              {filteredHistory.map((item) => (
                <div key={item.id} className="bg-[#0B0F1A] rounded-lg p-4 border border-blue-500/20">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <FileCode className="w-4 h-4 text-blue-400" />
                        <span className="text-white">Analysis #{item.id}</span>
                      </div>
                      <div className="flex items-center gap-2 text-sm text-gray-400">
                        <Calendar className="w-3 h-3" />
                        <span>{item.date}</span>
                      </div>
                    </div>
                    <span className={`px-3 py-1 rounded-full border text-sm ${getScoreBadge(item.quality_score)}`}>
                      {item.quality_score}
                    </span>
                  </div>

                  <div className="grid grid-cols-2 gap-2 mb-3 text-sm">
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400">Language:</span>
                      <span className="text-blue-400">{item.language}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400">Lines:</span>
                      <span className="text-gray-300">{item.linesOfCode}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400">Issues:</span>
                      <span className="text-gray-300">{item.issues}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400">Time:</span>
                      <span className="text-gray-300">{item.analysisTime}</span>
                    </div>
                  </div>

                  <div className="flex gap-2">
                    <button 
                      onClick={() => handleViewDetails(item)}
                      className="flex-1 px-3 py-2 bg-blue-500/20 text-blue-400 rounded-lg text-sm hover:bg-blue-500/30 transition-colors"
                    >
                      View
                    </button>
                    <button 
                      onClick={() => handleDownload(item)}
                      className="flex-1 px-3 py-2 bg-green-500/20 text-green-400 rounded-lg text-sm hover:bg-green-500/30 transition-colors"
                    >
                      Download
                    </button>
                    <button 
                      onClick={() => handleDelete(item.id)}
                      className="px-3 py-2 bg-red-500/20 text-red-400 rounded-lg text-sm hover:bg-red-500/30 transition-colors"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div className="glass-card p-12 rounded-xl text-center">
            <HistoryIcon className="w-16 h-16 text-gray-500 mx-auto mb-4" />
            <h3 className="text-xl text-white mb-2">No Analysis History</h3>
            <p className="text-gray-400">
              {selectedLanguageFilter === 'all' 
                ? 'Run code analysis to see your history here' 
                : `No ${selectedLanguageFilter} analysis found`}
            </p>
          </div>
        )}

        {/* Details Modal */}
        {showDetails && selectedAnalysis && (
          <div className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-4" onClick={() => setShowDetails(false)}>
            <div className="glass-card p-8 rounded-xl max-w-2xl w-full max-h-[80vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
              <div className="flex items-start justify-between mb-6">
                <h2 className="text-2xl text-white">Analysis Details</h2>
                <button 
                  onClick={() => setShowDetails(false)}
                  className="text-gray-400 hover:text-white transition-colors"
                >
                  ✕
                </button>
              </div>
              
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg text-blue-400 mb-2">Date & Time</h3>
                  <p className="text-gray-300">{selectedAnalysis.date}</p>
                </div>
                
                <div>
                  <h3 className="text-lg text-blue-400 mb-2">Quality Score</h3>
                  <p className={`text-2xl ${getScoreColor(selectedAnalysis.quality_score)}`}>
                    {selectedAnalysis.quality_score}/100
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg text-blue-400 mb-2">Issue Summary</h3>
                  <div className="grid grid-cols-3 gap-3">
                    <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3">
                      <p className="text-red-400 text-sm">Critical</p>
                      <p className="text-2xl text-white">{selectedAnalysis.critical}</p>
                    </div>
                    <div className="bg-orange-500/10 border border-orange-500/30 rounded-lg p-3">
                      <p className="text-orange-400 text-sm">High</p>
                      <p className="text-2xl text-white">{selectedAnalysis.high}</p>
                    </div>
                    <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-3">
                      <p className="text-yellow-400 text-sm">Medium</p>
                      <p className="text-2xl text-white">{selectedAnalysis.medium}</p>
                    </div>
                  </div>
                </div>
                
                <div>
                  <h3 className="text-lg text-blue-400 mb-2">Code Information</h3>
                  <div className="space-y-2">
                    <p className="text-gray-300">Language: <span className="text-white">{selectedAnalysis.language}</span></p>
                    <p className="text-gray-300">Lines of Code: <span className="text-white">{selectedAnalysis.linesOfCode}</span></p>
                    <p className="text-gray-300">Total Issues: <span className="text-white">{selectedAnalysis.issues}</span></p>
                  </div>
                </div>
              </div>
              
              <div className="flex gap-3 mt-6">
                <button 
                  onClick={() => {
                    handleDownload(selectedAnalysis);
                    setShowDetails(false);
                  }}
                  className="flex-1 gradient-button px-4 py-2 rounded-lg text-white"
                >
                  Download Report
                </button>
                <button 
                  onClick={() => setShowDetails(false)}
                  className="px-4 py-2 glass-card text-gray-300 hover:text-white rounded-lg transition-colors"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}